export enum PokeTypes {
  Normal = "normal",
  Fire = "fire",
  Water = "water",
  Electric = "electric",
  Grass = "grass",
  Ice = "ice",
  Fighting = "fighting",
  Poison = "poison",
  Ground = "ground",
  Flying = "flying",
  Psychic = "psychic",
  Bug = "bug",
  Rock = "rock",
  Ghost = "ghost",
  Dragon = "dragon",
  Dark = "dark",
  Steel = "steel",
  Fairy = "fairy",
}

export const PokeTypeStyles: Record<PokeTypes, { color: string }> = {
  [PokeTypes.Normal]: { color: "#A8A878" },
  [PokeTypes.Fire]: { color: "#F08030" },
  [PokeTypes.Water]: { color: "#6890F0" },
  [PokeTypes.Electric]: { color: "#F8D030" },
  [PokeTypes.Grass]: { color: "#78C850" },
  [PokeTypes.Ice]: { color: "#98D8D8" },
  [PokeTypes.Fighting]: { color: "#C03028" },
  [PokeTypes.Poison]: { color: "#A040A0" },
  [PokeTypes.Ground]: { color: "#E0C068" },
  [PokeTypes.Flying]: { color: "#A890F0" },
  [PokeTypes.Psychic]: { color: "#F85888" },
  [PokeTypes.Bug]: { color: "#A8B820" },
  [PokeTypes.Rock]: { color: "#B8A038" },
  [PokeTypes.Ghost]: { color: "#705898" },
  [PokeTypes.Dragon]: { color: "#7038F8" },
  [PokeTypes.Dark]: { color: "#705848" },
  [PokeTypes.Steel]: { color: "#B8B8D0" },
  [PokeTypes.Fairy]: { color: "#EE99AC" },
};
